# Generated by Django 5.0.4 on 2024-04-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='A', max_length=255, verbose_name='Name')),
                ('number', models.CharField(db_column='B', max_length=20, verbose_name='Number')),
                ('address', models.CharField(db_column='C', max_length=255, verbose_name='Address')),
            ],
        ),
    ]
