# Generated by Django 5.0.4 on 2024-04-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheetMapping', '0002_alter_contact_address_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=20, verbose_name='B'),
        ),
    ]
