# Generated by Django 5.0.4 on 2024-04-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheetMapping', '0004_alter_contact_options_alter_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
