# Generated by Django 5.0.4 on 2024-04-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheetMapping', '0005_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.TextField()),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('region', models.CharField(blank=True, max_length=32, null=True)),
                ('c_dates', models.TextField(blank=True, null=True)),
                ('dating_notes', models.TextField(blank=True, null=True)),
                ('dating_ref', models.TextField(blank=True, null=True)),
                ('card_analogue', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
