# Generated by Django 5.0.4 on 2024-04-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheetMapping', '0006_sitess_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sitess',
            new_name='Sites',
        ),
    ]
