# Generated by Django 5.0.4 on 2024-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheetMapping', '0007_rename_sitess_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='c_dates',
            field=models.TextField(blank=True, help_text='F', null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='card_analogue',
            field=models.IntegerField(blank=True, help_text='G', null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='code',
            field=models.CharField(db_index=True, help_text='E', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='dating_notes',
            field=models.TextField(blank=True, help_text='H', null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='dating_ref',
            field=models.TextField(blank=True, help_text='I', null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='latitude',
            field=models.FloatField(help_text='A'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='longitude',
            field=models.FloatField(help_text='B'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='name',
            field=models.TextField(help_text='D'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='region',
            field=models.CharField(blank=True, help_text='C', max_length=32, null=True),
        ),
    ]
